//USER REDUCER TYPES
export const SET_AUTHENTICATED = 'SET_AUTHENTICATED';
export const SET_UNAUTHENTICATED = 'SET_UNAUTHENTICATED';
export const SET_USER = 'SET_USER';
export const LOADING_USER = 'LOADING_USER';
export const SET_PROFILE = 'SET_PROFILE'
export const DELETE_PROFILE_CREATED = 'DELETE_PROFILE_CREATED';
export const SET_ERRORS_PROFILE = 'SET_ERRORS_PROFILE';
export const EDIT_PROFILE = 'EDIT_PROFILE'
export const JOB_DASHBOARD ='JOB_DASHBOARD'
export const DELETE_JOB = 'DELETE_JOB'
export const  EDIT_JOB = 'EDIT_JOB'
export const  RESET_USER = 'RESET_USER'
export const  GET_INBOX = 'GET_INBOX'
export const  CLEAR_INBOX = 'CLEAR_INBOX'
export const  DELETE_ITEM_INBOX ='DELETE_ITEM_INBOX'
export const  SEND_ITEM_INBOX ='SEND_ITEM_INBOX'




//UI REDUCER TYPES
export const SET_ERRORS = 'SET_ERRORS';
export const LOADING_UI = 'LOADING_UI';
export const CLEAR_ERRORS = 'CLEAR_ERRORS'
export const  RESET_UI = 'RESET_UI'
export const  SET_MESSAGE = 'SET_MESSAGE'
export const  CLEAR_MESSAGE = 'CLEAR_MESSAGE'

//DATA REDUCER TYPES
export const SEARCH_EMPLOYEE = 'SEARCH_EMPLOYEE';
export const SEARCH_JOBS = 'SEARCH_JOBS';
export const LOADING_DATA = 'LOADING_DATA';
export const NEW_SEARCH = 'NEW_SEARCH'
export const CLEAR_EMPLOYEES = 'CLEAR_EMPLOYEES'
export const CLEAR_JOBS = 'CLEAR_JOBS'
export const CLEAR_PROFILE = 'CLEAR_PROFILE'
export const GET_PROFILE = 'GET_PROFILE'
export const DELETE_PROFILE = 'DELETE_PROFILE'
export const ERROR_CLEAR_LOADING = 'ERROR_CLEAR_LOADING'
export const  RESET_DATA = 'RESET_DATA'